spring.application.name=nasa-space-media-explorer
server.port=8080
spring.datasource.url=jdbc:mysql://localhost:3306/nasa_media_explorer?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
nasa.api.key=cUP31vbbP42mGtgKz8KG8owTZWDzREY4ZOrkKDDH
nasa.api.base-url=https://api.nasa.gov
spring.data.web.pageable.max-page-size=100
spring.data.web.pageable.default-page-size=20
server.error.whitelabel.enabled=false
spring.mvc.throw-exception-if-no-handler-found=true